#!/bin/sh
git clone https://github.com/NovasomIndustries/Utils-1.0.5.git
git clone https://github.com/NovasomIndustries/Xcompiler-1.0.5.git

cd Qt
git clone https://github.com/NovasomIndustries/NOVAembed-1.0.5.git
HERE=`pwd`
cd /Devel/NOVAsom_SDK/Qt/build-NOVAembed-Desktop-Debug
make distclean
/usr/lib64/qt5/bin/qmake /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed.pro -r -spec linux-g++-64 CONFIG+=debug
make
cd /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed_P_Parser
rm -rf obj bin
mkdir -p obj bin/Debug
gcc -Wall -g  -c src/dts_gen.c -o obj/dts_gen.o
gcc -Wall -g  -c src/iomux.c -o obj/iomux.o
gcc -Wall -g  -c src/main.c -o obj/main.o
g++  -o bin/Debug/NOVAembed_P_Parser obj/dts_gen.o obj/iomux.o obj/main.o
cd /Devel/NOVAsom_SDK/Qt/NOVAembed/NOVAembed_U_Parser
rm -rf obj bin
mkdir -p obj bin/Debug
gcc -Wall -g  -c src/dts_gen.c -o obj/dts_gen.o
gcc -Wall -g  -c src/iomux.c -o obj/iomux.o
gcc -Wall -g  -c src/main.c -o obj/main.o
g++  -o bin/Debug/NOVAembed_U_Parser obj/dts_gen.o obj/iomux.o obj/main.o
cd ${HERE}
cd ..

cd Bootloader
git clone https://github.com/NovasomIndustries/u-boot-novasomU-2016.03_1.0.5.git
git clone https://github.com/NovasomIndustries/u-boot-novasomP-2015.04_1.0.5.git
git clone https://github.com/NovasomIndustries/u-boot-novasomM8-2017.11_1.0.5.git
git clone https://github.com/NovasomIndustries/u-boot-NOVAsomH5-2017.11_1.0.5.git
ln -s u-boot-NOVAsomH5-2017.11_1.0.5 u-boot-NOVAsomH5-2017.11
ln -s u-boot-novasomM8-2017.11_1.0.5 u-boot-novasomM8-2017.11
ln -s u-boot-novasomP-2015.04_1.0.5 u-boot-novasomP-2015.04
ln -s u-boot-novasomU-2016.03_1.0.5 u-boot-novasomU-2016.03
cd ..

cd Kernel
git clone https://github.com/NovasomIndustries/linux-allw-4.14.0_1.0.5.git
git clone https://github.com/NovasomIndustries/linux-4.11.0-QualcommLinaro_1.0.5.git
git clone https://github.com/NovasomIndustries/linux-imx_4.1.15_1.2.0_ga_1.0.5.git
git clone https://github.com/NovasomIndustries/linux-imx_4.1.43_1.0.5.git
ln -s  linux-4.11.0-QualcommLinaro_1.0.5 linux-4.11.0-QualcommLinaro
ln -s linux-allw-4.14.0_1.0.5 linux-allw-4.14.0
ln -s linux-imx_4.1.15_1.2.0_ga_1.0.5 linux-imx_4.1.15_1.2.0_ga
ln -s linux-imx_4.1.43_1.0.5 linux-imx_4.1.43




