#!/bin/sh
DISK=$1
FS=$2
FILENAME=`basename ${FS}`
echo -n "Extracting ${FILENAME} ... "
tar jxf ${FS}.img.tar.bz2 
echo "Done"
echo -n "Writing uSD ... "
sudo dd if=${FILENAME}.img of=${DISK} bs=4M
echo "Done"
rm ${FILENAME}.img
echo 0 > /tmp/result
return 0
