#!/bin/sh
# ${1} is number of user partition
# ${2} is size of first user partition, if enabled
# ${3} is size of second user partition, if enabled
# ${4} is the device
# ${5} is the dtb for solo/dl
# ${6} is the dtb for quad

. ./functions

DISK=${4}

SPL_FILE= "/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/SPL"
UBOOT_IMG="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04/NOVAsomP/u-boot.img"
KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-imx_4.1.15_1.2.0_ga/arch/arm/boot/zImage"
DTB_FILESDL="/Devel/NOVAsom_SDK/DtbUserWorkArea/${5}"
DTB_FILEQ="/Devel/NOVAsom_SDK/DtbUserWorkArea/${6}"
FILESYSTEM="/Devel/NOVAsom_SDK/Deploy/uInitrd"

echo "1" > /tmp/result

if [ ! -b ${DISK} ]; then
       echo "${DISK} not found"
       exit
fi

sudo umount ${DISK}* >/dev/null 2>&1
echo "Writing ${5} uSD"
sleep 1
sudo echo -n "Writing u-boot ... "
sudo dd if=/dev/zero of=${DISK} bs=4M count=1; sync
sudo dd if=${SPL_FILE} of=${DISK} bs=1k seek=1; sync
sync
echo "Done"

format_usd ${1} ${2} ${3} ${DISK}
if [ "$?" = "1" ]; then
	echo "Error formatting uSD!"
	exit
fi

rm -rf tmpmount
mkdir tmpmount
sleep 1
sudo mount ${DISK}1 tmpmount
[ "$?" != "0" ] && exit

echo -n "Copying `basename ${UBOOT_IMG}` ..."
sudo cp ${UBOOT_IMG} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying `basename ${KERNEL}` ..."
sudo cp ${KERNEL} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying `basename ${UINITRD}` ..."
sudo cp ${UINITRD} tmpmount/.
[ "$?" != "0" ] && exit

echo -n "Copying `basename ${DTB_FILEQ}` ..."
sudo cp ${DTB_FILEQ} tmpmount/imx6q-novasomP.dtb
echo -n "Copying `basename ${DTB_FILESDL}` ..."
sudo cp ${DTB_FILESDL} tmpmount/imx6sdl-novasomP.dtb
echo -n "`basename ${DTB_FILESDL}` "
echo "Done"

sudo umount tmpmount
sync

echo "0" > /tmp/result
echo "Write finished succesfully"
