#!/bin/bash
PREPEND_PATH="/Devel/NOVAsom_SDK"
KERNELS="Kernel/linux-4.11.0-QualcommLinaro_1.0.5 Kernel/linux-allw-4.14.0 Kernel/linux-imx_4.1.15_1.2.0_ga_1.0.5 Kernel/linux-imx_4.1.43_1.0.5"
DIRS="Utils-1.0.5 Xcompiler-1.0.5 Qt/NOVAembed-1.0.5 Bootloader/u-boot-novasomM8-2017.11_1.0.5 Bootloader/u-boot-novasomP-2015.04_1.0.5 Bootloader/u-boot-novasomU-2016.03_1.0.5 Bootloader/u-boot-NOVAsomH5-2017.11_1.0.5"
REPOCOUNT=`echo "$DIRS" | awk '{print NF}'`
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

HERE=`pwd`
COUNTMODS=0
COUNTSENT=0
INCREMENT=1
echo ""
for i in ${KERNELS}; do
	if [ -d ../${i} ]; then
		DIRS="${DIRS} ${i}"
	else
		printf "${RED}Skipping ${i} as not present${NC}\n"
	fi
done
echo ""

for i in ${DIRS}; do
        cd /Devel/NOVAsom_SDK/${i}
        BASE=`basename ${i}`
	printf "${GREEN}-----> On ${i} <-----${NC}\n"
	git status -s
done
echo ""
