#!/bin/sh
# $1 = kernel
# $2 = source me file
KERNEL=$1
SOURCEMEFILE=$2
DEFCONFIGFILE=$3
. ./${SOURCEMEFILE}
cd ../Kernel/${KERNEL}
make -j32 zImage
[ ! "$?" = "0" ] && return 1
make -j32 modules
[ ! "$?" = "0" ] && return 1
return 0
