#!/bin/sh
# $1 = source me file
# $2 = kernel
# $3 = defconfig file
SOURCEMEFILE=$1
KERNEL=$2
DEFCONFIGFILE=$3
. ./${SOURCEMEFILE}
cd ../Kernel/${KERNEL}
echo "1" > /tmp/result
make mrproper
make ${DEFCONFIGFILE}
[ ! "$?" = "0"] && exit
make -j32 zImage
[ ! "$?" = "0"] && exit
make -j32 modules
[ ! "$?" = "0"] && exit
echo "0" > /tmp/result
