#!/bin/sh
# $1 = source me file
# $2 = kernel
# $3 = defconfig file
SOURCEMEFILE=$1
KERNEL=$2
DEFCONFIGFILE=$3
. ./${SOURCEMEFILE}
cd ../Kernel/${KERNEL}
make mrproper
make ${DEFCONFIGFILE}
[ ! "$?" = "0" ] && return 1
make -j32 zImage
[ ! "$?" = "0" ] && return 1
make -j32 modules
[ ! "$?" = "0" ] && return 1
return 0
