#!/bin/sh
# $1 : file system name
# $3 : desired configuration
# $2 : board name
BR_VERSION="2017.11"
BR="buildroot-${BR_VERSION}"
BSP_DIR="FsBsp"

subst_config()
{
        SED_STRING="s/${1}=\([a-z]*\).*/${1}=\"${2}\"/g"
        cat .config | sed $SED_STRING > aa.config
        mv aa.config .config
}

echo "1" > /tmp/result
if [ "${1}" = "" ]; then
        echo "File system name is missing, givin' up"
        exit
fi
if [ -d ${1} ]; then
        rm -rf $1
fi

if [ "${3}" = "" ]; then
	case $2 in
		"P Series" ) 	BUILDROOT_CFG_BASE="PClass_Buildroot_Base.config"
				BUSYBOX_CFG_BASE="PClass_BusyBox_Base.config"
		;;
		"U Series" )	BUILDROOT_CFG_BASE="UClass_Buildroot_Base.config"
				BUSYBOX_CFG_BASE="UClass_BusyBox_Base.config"
		;;
		"M8 Series" )	BUILDROOT_CFG_BASE="M8Class_Buildroot_Base.config"
				BUSYBOX_CFG_BASE="M8Class_BusyBox_Base.config"
		;;
		* ) 		BUILDROOT_CFG_BASE="PClass_Buildroot_Base.config"
				BUSYBOX_CFG_BASE="PClass_BusyBox_Base.config"
		;;
	esac
else
        BUILDROOT_CFG_BASE=${3}
	case $2 in
		"P Series" ) BUSYBOX_CFG_BASE="PClass_BusyBox_Base.config"
		;;
		"U Series" ) BUSYBOX_CFG_BASE="UClass_BusyBox_Base.config"
		;;
		"M8 Series") BUSYBOX_CFG_BASE="M8Class_BusyBox_Base.config"
		;;
		* ) 	     BUSYBOX_CFG_BASE="PClass_BusyBox_Base.config"
		;;
	esac
fi

cd ../FileSystem
tar jxf ${BR}.tar.bz2
mv ${BR} ${1}
cd ${1}
cp -r ../../Utils/${BSP_DIR}/novasis board/novasis
echo `pwd`
cp ../../Utils/Configurations/${BUILDROOT_CFG_BASE} .config
cp ../../Utils/Configurations/${BUSYBOX_CFG_BASE} BusyBox.config

subst_config "BR2_TARGET_GENERIC_HOSTNAME" ${1}
subst_config "BR2_TARGET_GENERIC_ISSUE" "Welcome"
subst_config "BR2_PACKAGE_BUSYBOX_CONFIG" "\.\/BusyBox\.config"
cd ..
echo "Done"
echo 0 > /tmp/result


