#!/bin/sh
. ./SourceMe32_5
BOOT_P="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04"
cd ${BOOT_P}
export KBUILD_OUTPUT=./NOVAsomP
make distclean
make mrproper
make novasomp_defconfig
make -j32
if [ "$?" = "1"]; then
	echo "1" > /tmp/result
	return 1
fi
cd /Devel/NOVAsom_SDK/Deploy
rm -f u-boot.img SPL
ln -s ${BOOT_P}/NOVAsomP/u-boot.img
ln -s ${BOOT_P}/NOVAsomP/SPL
echo "0" > /tmp/result
return 0
