#!/bin/sh
. ./SourceMe64
cd /Devel/NOVAsom_SDK/Bootloader/u-boot-novasomM8-2017.11
echo "1" > /tmp/result
make distclean
[ "$?" != "0" ] && exit
make mrproper
[ "$?" != "0" ] && exit
make dragonboard410c_defconfig
[ "$?" != "0" ] && exit
make -j32
[ "$?" != "0" ] && exit
echo "0" > /tmp/result
