#!/bin/sh
# $1 = kernel
# $2 = source me file
# $3 = defconfig file

KERNEL=$1
SOURCEMEFILE=$2
DEFCONFIGFILE=$3
echo ${DEFCONFIGFILE}
. /Devel/NOVAsom_SDK/Utils/${SOURCEMEFILE}
cd /Devel/NOVAsom_SDK/Kernel/${KERNEL}
echo "1" > /tmp/result
make mrproper
make ${DEFCONFIGFILE}
[ ! "$?" = "0" ] && exit
make -j32 Image
[ ! "$?" = "0" ] && exit
make -j32 modules
[ ! "$?" = "0" ] && exit
make -j32 allwinner/novasom_m9.dtb
[ ! "$?" = "0" ] && exit

cp arch/arm64/boot/dts/allwinner/novasom_m9.dtb /Devel/NOVAsom_SDK/Deploy/.
cp arch/arm64/boot/Image /Devel/NOVAsom_SDK/Blobs/linux-allw-4.14.0_Image
cp arch/arm64/boot/Image /Devel/NOVAsom_SDK/Blobs/.
echo "0" > /tmp/result
