#!/bin/sh
. ../SourceMe64
BOOT_P="/Devel/NOVAsom_SDK/Bootloader/u-boot-NOVAsomH5-2017.11"
echo "1" > /tmp/result
cd ${BOOT_P}
export KBUILD_OUTPUT=./H5
make distclean
[ "$?" != "0" ] && exit
make mrproper
[ "$?" != "0" ] && exit
make orangepi_prime_defconfig
[ "$?" != "0" ] && exit
make -j32
[ "$?" != "0" ] && exit
echo "0" > /tmp/result
