#!/bin/sh
# ${1} is number of user partition
# ${2} is size of first user partition, if enabled
# ${3} is size of second user partition, if enabled
# ${4} is the device
# ${5} is the dtb
# ${6} is the NOVAsomParams file
# ${7} is the ramdisk size


KERNEL="/Devel/NOVAsom_SDK/Kernel/linux-4.11.0-QualcommLinaro/arch/arm/boot/zImage"
BOOTLOADER="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomM8-2017.11"
UINITRD="/Devel/NOVAsom_SDK/Deploy/uInitrd"
UBOOT_QCOM="${BOOTLOADER}/u-boot.img"
DISK=${4}
DTB="/Devel/NOVAsom_SDK/DtbUserWorkArea/${5}.dtb"
NOVASOMPARAMS="/Devel/NOVAsom_SDK/Utils/BootParameters/$6"
RAMDISK_SIZE="$7"

echo "1" > /tmp/result
#FILES="$UBOOT_QCOM $KERNEL $DTB $UINITRD $NOVASOMPARAMS"
#for i in ${FILES}; do
#        if ! [ -f ${i} ]; then
#                echo "File ${i} not found"
#                exit
#        fi
#done

if [ ! -b ${DISK} ]; then
	echo "${DISK} not found"
	exit
fi
sudo umount ${DISK}* >/dev/null 2>&1
echo "Writing NOVAsomM8 uSD"
sleep 1
sudo echo -n "Writing u-boot ... "
sudo ./mksdcard -o ${DISK} -p sdcard.txt -i qcom_bootloaders -s 2G
exit
echo y | sudo mkfs.vfat -F 16 ${DISK}7 -n BOOT
RET=$?
echo "mkfs.vfat returned $RET"
if ! [ "$?" = "0" ]; then
        echo "mkfs.vfat with error $RET"
        return 1
fi
sync
sudo dd if=${UBOOT_QCOM} of=${DISK}7

echo y | sudo mkfs.ext3 -t ext3 -L U6Config ${DISK}3
RET=$?
echo "mkfs.ext3 returned $RET"
if ! [ "$?" = "0" ]; then
	echo "mkfs.ext3 with error $RET"
	exit
fi

if [ "${1}" = "1" ]; then
	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}2
	RET=$?
	echo "mkfs.ext3 returned $RET"
	if ! [ "$?" = "0" ]; then
		echo "mkfs.ext3 with error $RET"
		exit
	fi
fi

if [ "${1}" = "2" ]; then
	echo y | sudo sudo mkfs.ext3 -t ext3 -L U6user1 ${DISK}4
	RET=$?
	echo "mkfs.ext3 returned $RET"
	if ! [ "$?" = "0" ]; then
		echo "mkfs.ext3 with error $RET"
		exit
	fi
	echo y | sudo mkfs.ext3 -t ext3 -L U6user2 ${DISK}4
	RET=$?
	echo "mkfs.ext3 returned $RET"
	if ! [ "$?" = "0" ]; then
		echo "mkfs.ext3 with error $RET"
		exit
	fi
fi

sync
sudo umount tmpmount >/dev/null 2>&1
rm -rf tmpmount
mkdir tmpmount
sleep 1
sudo mount ${DISK}1 tmpmount
[ "$?" != "0" ] && exit
sudo rm -rf tmpmount/*
[ "$?" != "0" ] && exit
echo `pwd`
echo -n "Copying novasomu.dtb ..."
sudo cp ${DTB} tmpmount/novasomu.dtb
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying u-boot files ..."
sudo cp ${UBOOT_QCOM} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying zImage ..."
sudo cp ${KERNEL} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying uInitrd ..."
sudo cp ${UINITRD} tmpmount/.
[ "$?" != "0" ] && exit
echo "Done"
echo -n "Copying `basename ${NOVASOMPARAMS}` ..."
echo "setramsize=setenv rdsize ${RAMDISK_SIZE}" > ../Deploy/NOVAsomParams
cat ${NOVASOMPARAMS} >> ../Deploy/NOVAsomParams
sudo cp ../Deploy/NOVAsomParams tmpmount/NOVAsomParams
[ "$?" != "0" ] && exit


#sudo cp ../../Bootloader/${BOOTLOADER}/ddr-test-uboot-jtag-mx6ull.bin tmpmount/.
#sudo cp ../../Bootloader/${BOOTLOADER}/qspi-header.bin tmpmount/qspi-header.bin
sudo umount tmpmount
sync
sudo umount ${DISK}
sync

echo "0" > /tmp/result
echo "Write finished succesfully"

