#!/bin/sh
# $1 = kernel
# $2 = source me file
# $3 = defconfig file

KERNEL=$1
SOURCEMEFILE=$2
DEFCONFIGFILE=$3
. /Devel/NOVAsom_SDK/Utils/${SOURCEMEFILE}
cd /Devel/NOVAsom_SDK/Kernel/${KERNEL}
echo "1" > /tmp/result
make mrproper
make ${DEFCONFIGFILE}
[ ! "$?" = "0" ] && exit
make -j32 zImage
[ ! "$?" = "0" ] && exit
make -j32 modules
[ ! "$?" = "0" ] && exit
if [ "$KERNEL" = "linux-imx_4.1.15_1.2.0_ga" ]; then
        cp arch/arm/boot/zImage /Devel/NOVAsom_SDK/Blobs/linux-nxp_p-4.1.15.2_zImage
else
        cp arch/arm/boot/zImage /Devel/NOVAsom_SDK/Blobs/linux-nxp_u-4.1.43_zImage
fi
cp arch/arm/boot/zImage /Devel/NOVAsom_SDK/Deploy/.
echo "0" > /tmp/result
