#!/bin/sh
. ../SourceMe32_5
BOOT_P="/Devel/NOVAsom_SDK/Bootloader/u-boot-novasomP-2015.04"
echo "1" > /tmp/result
cd ${BOOT_P}
export KBUILD_OUTPUT=./NOVAsomP
make distclean
[ "$?" != "0" ] && exit
make mrproper
[ "$?" != "0" ] && exit
make novasomp_defconfig
[ "$?" != "0" ] && exit
make -j32
[ "$?" != "0" ] && exit
cd /Devel/NOVAsom_SDK/Deploy
rm -f u-boot.img SPL
ln -s ${BOOT_P}/NOVAsomP/u-boot.img
ln -s ${BOOT_P}/NOVAsomP/SPL
echo "0" > /tmp/result
